name: 'Setup OpenVidu Call Backend'
description: 'Setup OpenVidu Call Backend for testing'
runs:
  using: 'composite'
  steps:
    - name: Clone OpenVidu Call Backend
      run: |
        git clone --depth 1 https://github.com/OpenVidu/openvidu-call
      shell: bash
    - name: Install and Start Backend
      run: |
        cd openvidu-call/backend
        npm install
        npm run dev:start &
      shell: bash
    - name: Wait for Backend to Start
      shell: bash
      run: wait-on --timeout 60000 http://localhost:6080/call/api/healthcheck
