name: openvidu-components-angular Tests

on:
  push:
    branches:
      - master
    paths:
      - 'openvidu-components-angular/**'
      - '.github/workflows/openvidu-components-angular-tests.yml'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: false
        default: ''

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Commit URL
        run: echo https://github.com/OpenVidu/openvidu/commit/${{ inputs.commit_sha || github.sha }}
      - name: Send Dispatch Event
        env:
          GITHUB_TOKEN: ${{ secrets.OPENVIDU_DISPATCH_EVENT_GA }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message || 'Manually' }}
          COMMIT_URL: ${{ github.event.commits[0].url || 'Manually' }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/OpenVidu/openvidu-call/dispatches \
          -d '{"event_type":"openvidu-components-angular","client_payload":{"commit-message":"'"$COMMIT_MESSAGE"'","commit-ref":"'"$COMMIT_URL"'", "branch-name":"'"$BRANCH_NAME"'"}}'

  nested_events:
    needs: test_setup
    name: Nested events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Install dependencies
        run: |
          cd openvidu-components-angular
          npm install
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Wait for openvidu-components-angular Testapp
        run: |
          until curl -s -f -o /dev/null http://localhost:4200; do
            echo "Waiting for openvidu-components-angular Testapp to be ready..."
            sleep 5
          done
      - name: Run nested components E2E event tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:nested-events --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  nested_structural_directives:
    needs: test_setup
    name: Nested Structural Directives
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run nested structural directives tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:nested-structural-directives --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  nested_attribute_directives:
    needs: test_setup
    name: Nested Attribute Directives
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run nested attribute directives tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:nested-attribute-directives --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_directives:
    needs: test_setup
    name: API Directives Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-directives --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_chat:
    needs: test_setup
    name: Chat E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-chat --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_events:
    needs: test_setup
    name: Events E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-events --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_media_devices:
    needs: test_setup
    name: Media devices E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-media-devices --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_panels:
    needs: test_setup
    name: Panels E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-panels --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  e2e_screen_sharing:
    needs: test_setup
    name: Screen sharing E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Build and Serve openvidu-components-angular Testapp
        uses: ./.github/actions/build-and-serve-components-testapp
      - name: Run Tests
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:lib-screensharing --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  webcomponent_e2e_stream:
    needs: test_setup
    name: Webcomponent stream
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Install dependencies
        run: |
          cd openvidu-components-angular
          npm install
      - name: Build openvidu-angular
        run: npm run lib:build --prefix openvidu-components-angular
      - name: Build openvidu-webcomponent
        run: npm run webcomponent:testing-build --prefix openvidu-components-angular
      - name: Serve Webcomponent Testapp
        run: npm run webcomponent:serve-testapp --prefix openvidu-components-angular &
      - name: Wait for openvidu-components-angular Testapp
        run: |
            until curl -s -f -o /dev/null http://localhost:8080; do
              echo "Waiting for openvidu-components-angular Testapp to be ready..."
              sleep 5
            done
      - name: Run Webcomponent E2E
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:webcomponent-stream --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  webcomponent_e2e_toolbar:
    needs: test_setup
    name: Webcomponent toolbar
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wait-on package
        run: npm install -g wait-on
      # - name: Run Browserless Chrome
      #   run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
      - name: Run Chrome
        run:  docker run --network=host -d -p 4444:4444 selenium/standalone-chrome:127.0
      - name: Run openvidu-local-deployment
        uses: ./.github/actions/setup-local-deployment
      - name: Setup OpenVidu Call Backend
        uses: ./.github/actions/setup-openvidu-call-backend
      - name: Install dependencies
        run: |
          cd openvidu-components-angular
          npm install
      - name: Build openvidu-angular
        run: npm run lib:build --prefix openvidu-components-angular
      - name: Build openvidu-webcomponent
        run: npm run webcomponent:testing-build --prefix openvidu-components-angular
      - name: Serve Webcomponent Testapp
        run: npm run webcomponent:serve-testapp --prefix openvidu-components-angular &
      - name: Wait for openvidu-components-angular Testapp
        run: |
            until curl -s -f -o /dev/null http://localhost:8080; do
              echo "Waiting for openvidu-components-angular Testapp to be ready..."
              sleep 5
            done
      - name: Run Webcomponent E2E
        env:
          LAUNCH_MODE: CI
        run: npm run e2e:webcomponent-toolbar --prefix openvidu-components-angular
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup